version: 1.2.5
environment:
  matrix:
    - IMAGE: 'Visual Studio 2022'
      RUNTIME: 'win-x64'
    - IMAGE: 'macOS'
      RUNTIME: 'osx-x64'
    - IMAGE: 'Ubuntu'
      RUNTIME: 'linux-x64'

  my_variable:
    secure: C0IqVjv+wrTqiWI4cNlCXKndiCX+No8WMcWcsUlUW3ycgeZrjsyAocYEzLI1UTNA

# this is ugly but it works mabye

build_script:
  - if "%IMAGE%"=="Visual Studio 2022" (
      dotnet restore StrayCatRunner/StrayCatRunner.csproj
    )
  - if "%IMAGE%"=="Visual Studio 2022" (
      dotnet build StrayCatRunner/StrayCatRunner.csproj --configuration Release
    )
  - if "%IMAGE%"=="Visual Studio 2022" (
      dotnet publish StrayCatRunner/StrayCatRunner.csproj --configuration Release --runtime %RUNTIME% /p:PublishSingleFile=true /p:PublishTrimmed=true /p:SelfContained=true --output ./publish/
    )
  - if "%IMAGE%"=="Visual Studio 2022" (
     xcopy /I /Y .\straycat_server.py .\publish\
    )
  - if "%IMAGE%"=="Visual Studio 2022" (
      7z a -r -tzip ./publish/StrayCatRunner_Windows.zip ./publish/* 
    )

  - if "%IMAGE%"=="macOS" (
      dotnet restore StrayCatRunner/StrayCatRunner.csproj
    )
  - if "%IMAGE%"=="macOS" (
      dotnet build StrayCatRunner/StrayCatRunner.csproj --configuration Release
    )
  - if "%IMAGE%"=="macOS" (
      dotnet publish StrayCatRunner/StrayCatRunner.csproj --configuration Release --runtime %RUNTIME% /p:PublishSingleFile=true /p:PublishTrimmed=true /p:SelfContained=true --output ./publish_mac/
    )
  - if "%IMAGE%"=="macOS" (
      xcopy /I /Y .\straycat_server.py ./publish_mac/
    )
  - if "%IMAGE%"=="macOS" (
      7z a -r -tzip ./publish/StrayCatRunner_Mac.zip ./publish_mac/* 
    )

  - if "%IMAGE%"=="Ubuntu" (
      dotnet restore StrayCatRunner/StrayCatRunner.csproj
    )
  - if "%IMAGE%"=="Ubuntu" (
      dotnet build StrayCatRunner/StrayCatRunner.csproj --configuration Release
    )
  - if "%IMAGE%"=="Ubuntu" (
      dotnet publish StrayCatRunner/StrayCatRunner.csproj --configuration Release --runtime %RUNTIME% /p:PublishSingleFile=true /p:PublishTrimmed=true /p:SelfContained=true --output ./publish_linux/
    )
  - if "%IMAGE%"=="Ubuntu" (
     xcopy /I /Y .\straycat_server.py ./publish_linux/
    )
  - if "%IMAGE%"=="Ubuntu" (
      7z a -r -tzip ./publish/StrayCatRunner_Linux.zip ./publish_linux/* 
    )

artifacts:
  - path: './publish/*.zip'
    name: Archives

deploy:
  - provider: GitHub
    tag: release
    release: Release
    description: 'This is a test release, supporting Windows, macOS, and Linux.'
    auth_token:
      secure: C0IqVjv+wrTqiWI4cNlCXKndiCX+No8WMcWcsUlUW3ycgeZrjsyAocYEzLI1UTNA
    artifact: Executable 
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: false